language: node_js
node_js:
  - 0.12.2
before_install:
  - npm install -g bower
  - npm install -g codeclimate-test-reporter
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
  - bower install
after_success:
  - ./scripts/release
branches:
  except:
    - RELEASE
    - /^\d+\.\d+\.\d+$/
addons:
  code_climate:
    repo_token:
      secure: "Fng7h8a5o8ti8w0lRjCjmpdI/YYQK1qRMfUFmev6oKzOGOATyMP4yJ7V3yuf+QPP5kAO23/gHkoQvKsbL7IyvHlwAqo4fHbwWHMF6ktURtxkRcs59P5kJunRht/C4Hyx9ZSmahHxv0WsmbxRGQ2dQJrgF2m71H7KrBXLwv+s+YVVAtEc6jGqVlVaalmrS4g2lWUQtRLcxSmFvqjigBDo4h5H2vqH1P0Qk1Xm8h7NTp3dq3c86l2hnzQFgfNJL0PjJPm/UKslwGoo35OQxejGvffVN9KV8ZgA0Ql52Zu3/UvdEvbzRv6QNxU6rJwjbfgKYD0oNGmKxRPo68aETtefRAju/sgY53HZP7Z0oZTGHQsBMrfQ2cJSopIetPWPw6sfd5WvFS4W0MPoAEVw8zcvUvBA4HZAHUP4y/k8FvYWDC/8G2YYXTeTEb1ATym0l7a67e8eWgvFC6fuOXLcVc49RftQOksbDTpnqOaqtWJxtw9WVkNFCSE1jXFCibxtaKAAIU05TCdypk4ita30dDJ2FFPP4wp/wmXaogj4rhCXlCPQx3em+Mpqr3yqEnt73dNQRMFEyfxubDMopodyUMbCdHv0CUqDpu173494wkO6wVg7rBnJqqAHXEJMI6bh5QtBa6MtmgOqVESaNcnxTaRAJ22hlhnIbVwp9Pl6uP0tMv8="
after_script:
  - codeclimate < coverage/lcov.info
